#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfbe1;
constexpr uint24_t FX_DATA_BYTES = 265813;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Images
{
  constexpr uint24_t Fire = 0x000000;
  constexpr uint16_t FireWidth  = 64;
  constexpr uint16_t FireHeight = 64;
  constexpr uint8_t  FireFrames = 16;

  constexpr uint24_t Title_Text = 0x002004;
  constexpr uint16_t Title_Text_width  = 57;
  constexpr uint16_t Title_Text_height = 64;

  constexpr uint24_t Title_Options = 0x002398;
  constexpr uint16_t Title_Options_width  = 17;
  constexpr uint16_t Title_Options_height = 64;

  constexpr uint24_t Skull_Large = 0x0024AC;
  constexpr uint16_t Skull_Large_width  = 52;
  constexpr uint16_t Skull_Large_height = 40;
  constexpr uint8_t  Skull_Large_frames = 4;

  constexpr uint24_t Skull_Eyes = 0x0028C0;
  constexpr uint16_t Skull_Eyes_width  = 10;
  constexpr uint16_t Skull_Eyes_height = 24;
  constexpr uint8_t  Skull_Eyes_frames = 48;

  constexpr uint24_t LevelEntry = 0x002E64;
  constexpr uint16_t LevelEntryWidth  = 70;
  constexpr uint16_t LevelEntryHeight = 64;

  constexpr uint24_t Dice_Roll = 0x0032C8;
  constexpr uint16_t Dice_Roll_width  = 12;
  constexpr uint16_t Dice_Roll_height = 16;
  constexpr uint8_t  Dice_Roll_frames = 9;

  constexpr uint24_t Dice_Black = 0x0033A4;
  constexpr uint16_t Dice_Black_width  = 12;
  constexpr uint16_t Dice_Black_height = 16;
  constexpr uint8_t  Dice_Black_frames = 7;

  constexpr uint24_t Dice_Fade = 0x003450;
  constexpr uint16_t Dice_Fade_width  = 12;
  constexpr uint16_t Dice_Fade_height = 16;
  constexpr uint8_t  Dice_Fade_frames = 60;

  constexpr uint24_t Background_00 = 0x0039F4;
  constexpr uint16_t Background_00_width  = 57;
  constexpr uint16_t Background_00_height = 64;

  constexpr uint24_t Background_02 = 0x003BC0;
  constexpr uint16_t Background_02_width  = 15;
  constexpr uint16_t Background_02_height = 64;

  constexpr uint24_t Button_PlayHand = 0x003C3C;
  constexpr uint16_t Button_PlayHand_width  = 24;
  constexpr uint16_t Button_PlayHand_height = 24;

  constexpr uint24_t Button_Reroll = 0x003C88;
  constexpr uint16_t Button_Reroll_width  = 24;
  constexpr uint16_t Button_Reroll_height = 24;

  constexpr uint24_t Swap = 0x003CD4;
  constexpr uint16_t SwapWidth  = 13;
  constexpr uint16_t SwapHeight = 64;

  constexpr uint24_t GameOver = 0x003D40;
  constexpr uint16_t GameOverWidth  = 128;
  constexpr uint16_t GameOverHeight = 64;

  constexpr uint24_t GameWin = 0x004544;
  constexpr uint16_t GameWinWidth  = 128;
  constexpr uint16_t GameWinHeight = 64;

  constexpr uint24_t Bones_Heading = 0x004D48;
  constexpr uint16_t Bones_Heading_width  = 14;
  constexpr uint16_t Bones_Heading_height = 32;

  constexpr uint24_t Hand_Names = 0x004D84;
  constexpr uint16_t Hand_Names_width  = 6;
  constexpr uint16_t Hand_Names_height = 36;
  constexpr uint8_t  Hand_Names_frames = 9;

  constexpr uint24_t Upgrade = 0x004E96;
  constexpr uint16_t UpgradeWidth  = 5;
  constexpr uint16_t UpgradeHeight = 32;

  constexpr uint24_t Total = 0x004EAE;
  constexpr uint16_t TotalWidth  = 5;
  constexpr uint16_t TotalHeight = 24;

  constexpr uint24_t Multiplier = 0x004EC1;
  constexpr uint16_t MultiplierWidth  = 5;
  constexpr uint16_t MultiplierHeight = 40;

  constexpr uint24_t Speech_Sml = 0x004EDE;
  constexpr uint16_t Speech_Sml_width  = 8;
  constexpr uint16_t Speech_Sml_height = 64;
  constexpr uint8_t  Speech_Sml_frames = 12;

  constexpr uint24_t Speech_Lrg = 0x0051E2;
  constexpr uint16_t Speech_Lrg_width  = 33;
  constexpr uint16_t Speech_Lrg_height = 64;
  constexpr uint8_t  Speech_Lrg_frames = 10;

  constexpr uint24_t SkullInfo_Top = 0x005C36;
  constexpr uint16_t SkullInfo_Top_width  = 16;
  constexpr uint16_t SkullInfo_Top_height = 64;

  constexpr uint24_t SkullInfo_Bot = 0x005CBA;
  constexpr uint16_t SkullInfo_Bot_width  = 16;
  constexpr uint16_t SkullInfo_Bot_height = 64;

  constexpr uint24_t HandScore_Top = 0x005D3E;
  constexpr uint16_t HandScore_Top_width  = 48;
  constexpr uint16_t HandScore_Top_height = 64;
  constexpr uint8_t  HandScore_Top_frames = 4;

  constexpr uint24_t HandScore_Bot = 0x006342;
  constexpr uint16_t HandScore_Bot_width  = 15;
  constexpr uint16_t HandScore_Bot_height = 64;
  constexpr uint8_t  HandScore_Bot_frames = 4;

  constexpr uint24_t Skeleton_Hand = 0x006526;
  constexpr uint16_t Skeleton_Hand_width  = 18;
  constexpr uint16_t Skeleton_Hand_height = 16;

  constexpr uint24_t Inventory_Top = 0x006572;
  constexpr uint16_t Inventory_Top_width  = 32;
  constexpr uint16_t Inventory_Top_height = 64;

  constexpr uint24_t Inventory_Bot = 0x006676;
  constexpr uint16_t Inventory_Bot_width  = 13;
  constexpr uint16_t Inventory_Bot_height = 64;
  constexpr uint8_t  Inventory_Bot_frames = 5;

  constexpr uint24_t UpgradeHand_Top = 0x006882;
  constexpr uint16_t UpgradeHand_Top_width  = 13;
  constexpr uint16_t UpgradeHand_Top_height = 64;

  constexpr uint24_t UpgradeHand_Bot = 0x0068EE;
  constexpr uint16_t UpgradeHand_Bot_width  = 15;
  constexpr uint16_t UpgradeHand_Bot_height = 64;
  constexpr uint8_t  UpgradeHand_Bot_frames = 3;

  constexpr uint24_t UpgradeHands = 0x006A5A;
  constexpr uint16_t UpgradeHandsWidth  = 24;
  constexpr uint16_t UpgradeHandsHeight = 64;
  constexpr uint8_t  UpgradeHandsFrames = 16;

  constexpr uint24_t UpgradeHand_Cursor = 0x00765E;
  constexpr uint16_t UpgradeHand_Cursor_width  = 29;
  constexpr uint16_t UpgradeHand_Cursor_height = 64;

  constexpr uint24_t SkullSelect_Top = 0x00774A;
  constexpr uint16_t SkullSelect_Top_width  = 13;
  constexpr uint16_t SkullSelect_Top_height = 64;

  constexpr uint24_t SkullSelect_Bot = 0x0077B6;
  constexpr uint16_t SkullSelect_Bot_width  = 13;
  constexpr uint16_t SkullSelect_Bot_height = 64;

  constexpr uint24_t Skull_Names = 0x007822;
  constexpr uint16_t Skull_Names_width  = 6;
  constexpr uint16_t Skull_Names_height = 41;
  constexpr uint8_t  Skull_Names_frames = 20;

  constexpr uint24_t Skull_Cursor = 0x007AF6;
  constexpr uint16_t Skull_Cursor_width  = 48;
  constexpr uint16_t Skull_Cursor_height = 64;

  constexpr uint24_t Skull_00 = 0x007C7A;
  constexpr uint16_t Skull_00_width  = 48;
  constexpr uint16_t Skull_00_height = 64;

  constexpr uint24_t Skull_01 = 0x007DFE;
  constexpr uint16_t Skull_01_width  = 48;
  constexpr uint16_t Skull_01_height = 64;

  constexpr uint24_t Skull_02 = 0x007F82;
  constexpr uint16_t Skull_02_width  = 48;
  constexpr uint16_t Skull_02_height = 64;

  constexpr uint24_t Skull_03 = 0x008106;
  constexpr uint16_t Skull_03_width  = 48;
  constexpr uint16_t Skull_03_height = 64;

  constexpr uint24_t Skull_04 = 0x00828A;
  constexpr uint16_t Skull_04_width  = 48;
  constexpr uint16_t Skull_04_height = 64;

  constexpr uint24_t Skull_05 = 0x00840E;
  constexpr uint16_t Skull_05_width  = 48;
  constexpr uint16_t Skull_05_height = 64;

  constexpr uint24_t Skull_06 = 0x008592;
  constexpr uint16_t Skull_06_width  = 48;
  constexpr uint16_t Skull_06_height = 64;

  constexpr uint24_t Skull_07 = 0x008716;
  constexpr uint16_t Skull_07_width  = 48;
  constexpr uint16_t Skull_07_height = 64;

  constexpr uint24_t Skull_08 = 0x00889A;
  constexpr uint16_t Skull_08_width  = 48;
  constexpr uint16_t Skull_08_height = 64;

  constexpr uint24_t Skull_09 = 0x008A1E;
  constexpr uint16_t Skull_09_width  = 48;
  constexpr uint16_t Skull_09_height = 64;

  constexpr uint24_t Skull_10 = 0x008BA2;
  constexpr uint16_t Skull_10_width  = 48;
  constexpr uint16_t Skull_10_height = 64;

  constexpr uint24_t Skull_11 = 0x008D26;
  constexpr uint16_t Skull_11_width  = 48;
  constexpr uint16_t Skull_11_height = 64;

  constexpr uint24_t Skull_12 = 0x008EAA;
  constexpr uint16_t Skull_12_width  = 48;
  constexpr uint16_t Skull_12_height = 64;

  constexpr uint24_t Skull_13 = 0x00902E;
  constexpr uint16_t Skull_13_width  = 48;
  constexpr uint16_t Skull_13_height = 64;

  constexpr uint24_t Skull_14 = 0x0091B2;
  constexpr uint16_t Skull_14_width  = 48;
  constexpr uint16_t Skull_14_height = 64;

  constexpr uint24_t Skull_15 = 0x009336;
  constexpr uint16_t Skull_15_width  = 48;
  constexpr uint16_t Skull_15_height = 64;

  constexpr uint24_t Skull_16 = 0x0094BA;
  constexpr uint16_t Skull_16_width  = 48;
  constexpr uint16_t Skull_16_height = 64;

  constexpr uint24_t Skull_17 = 0x00963E;
  constexpr uint16_t Skull_17_width  = 48;
  constexpr uint16_t Skull_17_height = 64;

  constexpr uint24_t Skull_18 = 0x0097C2;
  constexpr uint16_t Skull_18_width  = 48;
  constexpr uint16_t Skull_18_height = 64;

  constexpr uint24_t Skull_19 = 0x009946;
  constexpr uint16_t Skull_19_width  = 48;
  constexpr uint16_t Skull_19_height = 64;

  constexpr uint24_t Skull_Thumb_00 = 0x009ACA;
  constexpr uint16_t Skull_Thumb_00_width  = 23;
  constexpr uint16_t Skull_Thumb_00_height = 64;

  constexpr uint24_t Skull_Thumb_01 = 0x009B86;
  constexpr uint16_t Skull_Thumb_01_width  = 23;
  constexpr uint16_t Skull_Thumb_01_height = 64;

  constexpr uint24_t Skull_Thumb_02 = 0x009C42;
  constexpr uint16_t Skull_Thumb_02_width  = 23;
  constexpr uint16_t Skull_Thumb_02_height = 64;

  constexpr uint24_t Skull_Thumb_03 = 0x009CFE;
  constexpr uint16_t Skull_Thumb_03_width  = 23;
  constexpr uint16_t Skull_Thumb_03_height = 64;

  constexpr uint24_t Skull_Thumb_04 = 0x009DBA;
  constexpr uint16_t Skull_Thumb_04_width  = 23;
  constexpr uint16_t Skull_Thumb_04_height = 64;

  constexpr uint24_t Skull_Thumb_05 = 0x009E76;
  constexpr uint16_t Skull_Thumb_05_width  = 23;
  constexpr uint16_t Skull_Thumb_05_height = 64;

  constexpr uint24_t Skull_Thumb_06 = 0x009F32;
  constexpr uint16_t Skull_Thumb_06_width  = 23;
  constexpr uint16_t Skull_Thumb_06_height = 64;

  constexpr uint24_t Skull_Thumb_07 = 0x009FEE;
  constexpr uint16_t Skull_Thumb_07_width  = 23;
  constexpr uint16_t Skull_Thumb_07_height = 64;

  constexpr uint24_t Skull_Thumb_08 = 0x00A0AA;
  constexpr uint16_t Skull_Thumb_08_width  = 23;
  constexpr uint16_t Skull_Thumb_08_height = 64;

  constexpr uint24_t Skull_Thumb_09 = 0x00A166;
  constexpr uint16_t Skull_Thumb_09_width  = 23;
  constexpr uint16_t Skull_Thumb_09_height = 64;

  constexpr uint24_t Skull_Thumb_10 = 0x00A222;
  constexpr uint16_t Skull_Thumb_10_width  = 23;
  constexpr uint16_t Skull_Thumb_10_height = 64;

  constexpr uint24_t Skull_Thumb_11 = 0x00A2DE;
  constexpr uint16_t Skull_Thumb_11_width  = 23;
  constexpr uint16_t Skull_Thumb_11_height = 64;

  constexpr uint24_t Skull_Thumb_12 = 0x00A39A;
  constexpr uint16_t Skull_Thumb_12_width  = 23;
  constexpr uint16_t Skull_Thumb_12_height = 64;

  constexpr uint24_t Skull_Thumb_13 = 0x00A456;
  constexpr uint16_t Skull_Thumb_13_width  = 23;
  constexpr uint16_t Skull_Thumb_13_height = 64;

  constexpr uint24_t Skull_Thumb_14 = 0x00A512;
  constexpr uint16_t Skull_Thumb_14_width  = 23;
  constexpr uint16_t Skull_Thumb_14_height = 64;

  constexpr uint24_t Skull_Thumb_15 = 0x00A5CE;
  constexpr uint16_t Skull_Thumb_15_width  = 23;
  constexpr uint16_t Skull_Thumb_15_height = 64;

  constexpr uint24_t Skull_Thumb_16 = 0x00A68A;
  constexpr uint16_t Skull_Thumb_16_width  = 23;
  constexpr uint16_t Skull_Thumb_16_height = 64;

  constexpr uint24_t Skull_Thumb_17 = 0x00A746;
  constexpr uint16_t Skull_Thumb_17_width  = 23;
  constexpr uint16_t Skull_Thumb_17_height = 64;

  constexpr uint24_t Skull_Thumb_18 = 0x00A802;
  constexpr uint16_t Skull_Thumb_18_width  = 23;
  constexpr uint16_t Skull_Thumb_18_height = 64;

  constexpr uint24_t Skull_Thumb_19 = 0x00A8BE;
  constexpr uint16_t Skull_Thumb_19_width  = 23;
  constexpr uint16_t Skull_Thumb_19_height = 64;

  constexpr uint24_t Skull_Thumb_Cursor = 0x00A97A;
  constexpr uint16_t Skull_Thumb_Cursor_width  = 23;
  constexpr uint16_t Skull_Thumb_Cursor_height = 64;

  constexpr uint24_t Skulls = 0x00AA36;
  constexpr uint24_t Skulls_Thumb = 0x00AA72;
  constexpr uint24_t Zoom_01 = 0x00AAAE;
  constexpr uint16_t Zoom_01_width  = 128;
  constexpr uint16_t Zoom_01_height = 64;

  constexpr uint24_t Zoom_02 = 0x00B2B2;
  constexpr uint16_t Zoom_02_width  = 128;
  constexpr uint16_t Zoom_02_height = 64;

  constexpr uint24_t Zoom_03 = 0x00BAB6;
  constexpr uint16_t Zoom_03_width  = 128;
  constexpr uint16_t Zoom_03_height = 64;

  constexpr uint24_t Zoom_04 = 0x00C2BA;
  constexpr uint16_t Zoom_04_width  = 128;
  constexpr uint16_t Zoom_04_height = 64;

  constexpr uint24_t Zoom_05 = 0x00CABE;
  constexpr uint16_t Zoom_05_width  = 128;
  constexpr uint16_t Zoom_05_height = 64;

  constexpr uint24_t Zoom_06 = 0x00D2C2;
  constexpr uint16_t Zoom_06_width  = 128;
  constexpr uint16_t Zoom_06_height = 64;

  constexpr uint24_t Zoom_07 = 0x00DAC6;
  constexpr uint16_t Zoom_07_width  = 128;
  constexpr uint16_t Zoom_07_height = 64;

  constexpr uint24_t Zoom_08 = 0x00E2CA;
  constexpr uint16_t Zoom_08_width  = 128;
  constexpr uint16_t Zoom_08_height = 64;

  constexpr uint24_t Zoom_09 = 0x00EACE;
  constexpr uint16_t Zoom_09_width  = 128;
  constexpr uint16_t Zoom_09_height = 64;

  constexpr uint24_t Zoom_10 = 0x00F2D2;
  constexpr uint16_t Zoom_10_width  = 128;
  constexpr uint16_t Zoom_10_height = 64;

  constexpr uint24_t Zoom_11 = 0x00FAD6;
  constexpr uint16_t Zoom_11_width  = 128;
  constexpr uint16_t Zoom_11_height = 64;

  constexpr uint24_t Zoom_12 = 0x0102DA;
  constexpr uint16_t Zoom_12_width  = 128;
  constexpr uint16_t Zoom_12_height = 64;

  constexpr uint24_t Zoom_13 = 0x010ADE;
  constexpr uint16_t Zoom_13_width  = 128;
  constexpr uint16_t Zoom_13_height = 64;

  constexpr uint24_t Zoom_14 = 0x0112E2;
  constexpr uint16_t Zoom_14_width  = 128;
  constexpr uint16_t Zoom_14_height = 64;

  constexpr uint24_t Zoom_15 = 0x011AE6;
  constexpr uint16_t Zoom_15_width  = 128;
  constexpr uint16_t Zoom_15_height = 64;

  constexpr uint24_t Zoom_16 = 0x0122EA;
  constexpr uint16_t Zoom_16_width  = 128;
  constexpr uint16_t Zoom_16_height = 64;

  constexpr uint24_t Zoom_17 = 0x012AEE;
  constexpr uint16_t Zoom_17_width  = 128;
  constexpr uint16_t Zoom_17_height = 64;

  constexpr uint24_t Zoom_18 = 0x0132F2;
  constexpr uint16_t Zoom_18_width  = 128;
  constexpr uint16_t Zoom_18_height = 64;

  constexpr uint24_t Zoom_19 = 0x013AF6;
  constexpr uint16_t Zoom_19_width  = 128;
  constexpr uint16_t Zoom_19_height = 64;

  constexpr uint24_t Zoom_20 = 0x0142FA;
  constexpr uint16_t Zoom_20_width  = 128;
  constexpr uint16_t Zoom_20_height = 64;

  constexpr uint24_t Zoom_21 = 0x014AFE;
  constexpr uint16_t Zoom_21_width  = 128;
  constexpr uint16_t Zoom_21_height = 64;

  constexpr uint24_t Zoom_22 = 0x015302;
  constexpr uint16_t Zoom_22_width  = 128;
  constexpr uint16_t Zoom_22_height = 64;

  constexpr uint24_t Zoom_23 = 0x015B06;
  constexpr uint16_t Zoom_23_width  = 128;
  constexpr uint16_t Zoom_23_height = 64;

  constexpr uint24_t Zoom_24 = 0x01630A;
  constexpr uint16_t Zoom_24_width  = 128;
  constexpr uint16_t Zoom_24_height = 64;

  constexpr uint24_t Zoom_25 = 0x016B0E;
  constexpr uint16_t Zoom_25_width  = 128;
  constexpr uint16_t Zoom_25_height = 64;

  constexpr uint24_t Zoom_26 = 0x017312;
  constexpr uint16_t Zoom_26_width  = 128;
  constexpr uint16_t Zoom_26_height = 64;

  constexpr uint24_t Zoom_27 = 0x017B16;
  constexpr uint16_t Zoom_27_width  = 128;
  constexpr uint16_t Zoom_27_height = 64;

  constexpr uint24_t Zoom_28 = 0x01831A;
  constexpr uint16_t Zoom_28_width  = 128;
  constexpr uint16_t Zoom_28_height = 64;

  constexpr uint24_t Zoom_29 = 0x018B1E;
  constexpr uint16_t Zoom_29_width  = 128;
  constexpr uint16_t Zoom_29_height = 64;

  constexpr uint24_t Zoom_30 = 0x019322;
  constexpr uint16_t Zoom_30_width  = 128;
  constexpr uint16_t Zoom_30_height = 64;

  constexpr uint24_t Zoom_31 = 0x019B26;
  constexpr uint16_t Zoom_31_width  = 128;
  constexpr uint16_t Zoom_31_height = 64;

  constexpr uint24_t Zoom_32 = 0x01A32A;
  constexpr uint16_t Zoom_32_width  = 128;
  constexpr uint16_t Zoom_32_height = 64;

  constexpr uint24_t Zoom_33 = 0x01AB2E;
  constexpr uint16_t Zoom_33_width  = 128;
  constexpr uint16_t Zoom_33_height = 64;

  constexpr uint24_t Zoom_34 = 0x01B332;
  constexpr uint16_t Zoom_34_width  = 128;
  constexpr uint16_t Zoom_34_height = 64;

  constexpr uint24_t Zoom_35 = 0x01BB36;
  constexpr uint16_t Zoom_35_width  = 128;
  constexpr uint16_t Zoom_35_height = 64;

  constexpr uint24_t Zoom_36 = 0x01C33A;
  constexpr uint16_t Zoom_36_width  = 128;
  constexpr uint16_t Zoom_36_height = 64;

  constexpr uint24_t Zoom_37 = 0x01CB3E;
  constexpr uint16_t Zoom_37_width  = 128;
  constexpr uint16_t Zoom_37_height = 64;

  constexpr uint24_t Zoom_38 = 0x01D342;
  constexpr uint16_t Zoom_38_width  = 128;
  constexpr uint16_t Zoom_38_height = 64;

  constexpr uint24_t Zoom_39 = 0x01DB46;
  constexpr uint16_t Zoom_39_width  = 128;
  constexpr uint16_t Zoom_39_height = 64;

  constexpr uint24_t Zoom_40 = 0x01E34A;
  constexpr uint16_t Zoom_40_width  = 128;
  constexpr uint16_t Zoom_40_height = 64;

  constexpr uint24_t Zoom_41 = 0x01EB4E;
  constexpr uint16_t Zoom_41_width  = 128;
  constexpr uint16_t Zoom_41_height = 64;

  constexpr uint24_t Zoom_42 = 0x01F352;
  constexpr uint16_t Zoom_42_width  = 128;
  constexpr uint16_t Zoom_42_height = 64;

  constexpr uint24_t Zoom_43 = 0x01FB56;
  constexpr uint16_t Zoom_43_width  = 128;
  constexpr uint16_t Zoom_43_height = 64;

  constexpr uint24_t Zoom_44 = 0x02035A;
  constexpr uint16_t Zoom_44_width  = 128;
  constexpr uint16_t Zoom_44_height = 64;

  constexpr uint24_t Zoom_45 = 0x020B5E;
  constexpr uint16_t Zoom_45_width  = 128;
  constexpr uint16_t Zoom_45_height = 64;

  constexpr uint24_t Zoom_46 = 0x021362;
  constexpr uint16_t Zoom_46_width  = 128;
  constexpr uint16_t Zoom_46_height = 64;

  constexpr uint24_t Zoom_47 = 0x021B66;
  constexpr uint16_t Zoom_47_width  = 128;
  constexpr uint16_t Zoom_47_height = 64;

  constexpr uint24_t Zoom_48 = 0x02236A;
  constexpr uint16_t Zoom_48_width  = 128;
  constexpr uint16_t Zoom_48_height = 64;

  constexpr uint24_t Zoom_49 = 0x02276E;
  constexpr uint16_t Zoom_49_width  = 128;
  constexpr uint16_t Zoom_49_height = 64;

  constexpr uint24_t Zoom_50 = 0x022B72;
  constexpr uint16_t Zoom_50_width  = 128;
  constexpr uint16_t Zoom_50_height = 64;

  constexpr uint24_t Drip_01 = 0x022F76;
  constexpr uint16_t Drip_01_width  = 128;
  constexpr uint16_t Drip_01_height = 64;

  constexpr uint24_t Drip_02 = 0x02337A;
  constexpr uint16_t Drip_02_width  = 128;
  constexpr uint16_t Drip_02_height = 64;

  constexpr uint24_t Drip_03 = 0x023B7E;
  constexpr uint16_t Drip_03_width  = 128;
  constexpr uint16_t Drip_03_height = 64;

  constexpr uint24_t Drip_04 = 0x024382;
  constexpr uint16_t Drip_04_width  = 128;
  constexpr uint16_t Drip_04_height = 64;

  constexpr uint24_t Drip_05 = 0x024B86;
  constexpr uint16_t Drip_05_width  = 128;
  constexpr uint16_t Drip_05_height = 64;

  constexpr uint24_t Drip_06 = 0x02538A;
  constexpr uint16_t Drip_06_width  = 128;
  constexpr uint16_t Drip_06_height = 64;

  constexpr uint24_t Drip_07 = 0x025B8E;
  constexpr uint16_t Drip_07_width  = 128;
  constexpr uint16_t Drip_07_height = 64;

  constexpr uint24_t Drip_08 = 0x026392;
  constexpr uint16_t Drip_08_width  = 128;
  constexpr uint16_t Drip_08_height = 64;

  constexpr uint24_t Drip_09 = 0x026B96;
  constexpr uint16_t Drip_09_width  = 128;
  constexpr uint16_t Drip_09_height = 64;

  constexpr uint24_t Drip_10 = 0x02739A;
  constexpr uint16_t Drip_10_width  = 128;
  constexpr uint16_t Drip_10_height = 64;

  constexpr uint24_t Drip_11 = 0x027B9E;
  constexpr uint16_t Drip_11_width  = 128;
  constexpr uint16_t Drip_11_height = 64;

  constexpr uint24_t Drip_12 = 0x0283A2;
  constexpr uint16_t Drip_12_width  = 128;
  constexpr uint16_t Drip_12_height = 64;

  constexpr uint24_t Drip_13 = 0x028BA6;
  constexpr uint16_t Drip_13_width  = 128;
  constexpr uint16_t Drip_13_height = 64;

  constexpr uint24_t Drip_14 = 0x0293AA;
  constexpr uint16_t Drip_14_width  = 128;
  constexpr uint16_t Drip_14_height = 64;

  constexpr uint24_t Drip_15 = 0x029BAE;
  constexpr uint16_t Drip_15_width  = 128;
  constexpr uint16_t Drip_15_height = 64;

  constexpr uint24_t Drip_16 = 0x02A3B2;
  constexpr uint16_t Drip_16_width  = 128;
  constexpr uint16_t Drip_16_height = 64;

  constexpr uint24_t Drip_17 = 0x02ABB6;
  constexpr uint16_t Drip_17_width  = 128;
  constexpr uint16_t Drip_17_height = 64;

  constexpr uint24_t Drip_18 = 0x02B3BA;
  constexpr uint16_t Drip_18_width  = 128;
  constexpr uint16_t Drip_18_height = 64;

  constexpr uint24_t Drip_19 = 0x02BBBE;
  constexpr uint16_t Drip_19_width  = 128;
  constexpr uint16_t Drip_19_height = 64;

  constexpr uint24_t Drip_20 = 0x02C3C2;
  constexpr uint16_t Drip_20_width  = 128;
  constexpr uint16_t Drip_20_height = 64;

  constexpr uint24_t Drip_21 = 0x02CBC6;
  constexpr uint16_t Drip_21_width  = 128;
  constexpr uint16_t Drip_21_height = 64;

  constexpr uint24_t Drip_22 = 0x02D3CA;
  constexpr uint16_t Drip_22_width  = 128;
  constexpr uint16_t Drip_22_height = 64;

  constexpr uint24_t Drip_23 = 0x02DBCE;
  constexpr uint16_t Drip_23_width  = 128;
  constexpr uint16_t Drip_23_height = 64;

  constexpr uint24_t Drip_24 = 0x02E3D2;
  constexpr uint16_t Drip_24_width  = 128;
  constexpr uint16_t Drip_24_height = 64;

  constexpr uint24_t Drip_25 = 0x02EBD6;
  constexpr uint16_t Drip_25_width  = 128;
  constexpr uint16_t Drip_25_height = 64;

  constexpr uint24_t Drip_26 = 0x02F3DA;
  constexpr uint16_t Drip_26_width  = 128;
  constexpr uint16_t Drip_26_height = 64;

  constexpr uint24_t Drip_27 = 0x02FBDE;
  constexpr uint16_t Drip_27_width  = 128;
  constexpr uint16_t Drip_27_height = 64;

  constexpr uint24_t Drip_28 = 0x0303E2;
  constexpr uint16_t Drip_28_width  = 128;
  constexpr uint16_t Drip_28_height = 64;

  constexpr uint24_t Drip_29 = 0x030BE6;
  constexpr uint16_t Drip_29_width  = 128;
  constexpr uint16_t Drip_29_height = 64;

  constexpr uint24_t Drip_30 = 0x0313EA;
  constexpr uint16_t Drip_30_width  = 128;
  constexpr uint16_t Drip_30_height = 64;

  constexpr uint24_t Drip_31 = 0x031BEE;
  constexpr uint16_t Drip_31_width  = 128;
  constexpr uint16_t Drip_31_height = 64;

  constexpr uint24_t Drip_32 = 0x0323F2;
  constexpr uint16_t Drip_32_width  = 128;
  constexpr uint16_t Drip_32_height = 64;

  constexpr uint24_t Drip_33 = 0x032BF6;
  constexpr uint16_t Drip_33_width  = 128;
  constexpr uint16_t Drip_33_height = 64;

  constexpr uint24_t Drip_34 = 0x0333FA;
  constexpr uint16_t Drip_34_width  = 128;
  constexpr uint16_t Drip_34_height = 64;

  constexpr uint24_t Drip_35 = 0x033BFE;
  constexpr uint16_t Drip_35_width  = 128;
  constexpr uint16_t Drip_35_height = 64;

  constexpr uint24_t Drip_36 = 0x034402;
  constexpr uint16_t Drip_36_width  = 128;
  constexpr uint16_t Drip_36_height = 64;

  constexpr uint24_t Drip_37 = 0x034C06;
  constexpr uint16_t Drip_37_width  = 128;
  constexpr uint16_t Drip_37_height = 64;

  constexpr uint24_t Drip_38 = 0x03540A;
  constexpr uint16_t Drip_38_width  = 128;
  constexpr uint16_t Drip_38_height = 64;

  constexpr uint24_t Drip_39 = 0x035C0E;
  constexpr uint16_t Drip_39_width  = 128;
  constexpr uint16_t Drip_39_height = 64;

  constexpr uint24_t Drip_40 = 0x036412;
  constexpr uint16_t Drip_40_width  = 128;
  constexpr uint16_t Drip_40_height = 64;

  constexpr uint24_t Drip_41 = 0x036C16;
  constexpr uint16_t Drip_41_width  = 128;
  constexpr uint16_t Drip_41_height = 64;

  constexpr uint24_t Drip_42 = 0x03741A;
  constexpr uint16_t Drip_42_width  = 128;
  constexpr uint16_t Drip_42_height = 64;

  constexpr uint24_t Drip_43 = 0x037C1E;
  constexpr uint16_t Drip_43_width  = 128;
  constexpr uint16_t Drip_43_height = 64;

  constexpr uint24_t Drip_44 = 0x038422;
  constexpr uint16_t Drip_44_width  = 128;
  constexpr uint16_t Drip_44_height = 64;

  constexpr uint24_t Drip_45 = 0x038C26;
  constexpr uint16_t Drip_45_width  = 128;
  constexpr uint16_t Drip_45_height = 64;

  constexpr uint24_t Drip_46 = 0x03942A;
  constexpr uint16_t Drip_46_width  = 128;
  constexpr uint16_t Drip_46_height = 64;

  constexpr uint24_t Drip_47 = 0x039C2E;
  constexpr uint16_t Drip_47_width  = 128;
  constexpr uint16_t Drip_47_height = 64;

  constexpr uint24_t Drip_48 = 0x03A432;
  constexpr uint16_t Drip_48_width  = 128;
  constexpr uint16_t Drip_48_height = 64;

  constexpr uint24_t Drip_49 = 0x03AC36;
  constexpr uint16_t Drip_49_width  = 128;
  constexpr uint16_t Drip_49_height = 64;

  constexpr uint24_t Drip_50 = 0x03B43A;
  constexpr uint16_t Drip_50_width  = 128;
  constexpr uint16_t Drip_50_height = 64;

  constexpr uint24_t Drip_51 = 0x03BC3E;
  constexpr uint16_t Drip_51_width  = 128;
  constexpr uint16_t Drip_51_height = 64;

  constexpr uint24_t Drip_52 = 0x03C442;
  constexpr uint16_t Drip_52_width  = 128;
  constexpr uint16_t Drip_52_height = 64;

  constexpr uint24_t Drip_53 = 0x03CC46;
  constexpr uint16_t Drip_53_width  = 128;
  constexpr uint16_t Drip_53_height = 64;

  constexpr uint24_t Drip_54 = 0x03D44A;
  constexpr uint16_t Drip_54_width  = 128;
  constexpr uint16_t Drip_54_height = 64;

  constexpr uint24_t Drip_55 = 0x03DC4E;
  constexpr uint16_t Drip_55_width  = 128;
  constexpr uint16_t Drip_55_height = 64;

  constexpr uint24_t Drip_56 = 0x03E452;
  constexpr uint16_t Drip_56_width  = 128;
  constexpr uint16_t Drip_56_height = 64;

  constexpr uint24_t Drip_57 = 0x03EC56;
  constexpr uint16_t Drip_57_width  = 128;
  constexpr uint16_t Drip_57_height = 64;

  constexpr uint24_t Drip_58 = 0x03F45A;
  constexpr uint16_t Drip_58_width  = 128;
  constexpr uint16_t Drip_58_height = 64;

  constexpr uint24_t Drip_59 = 0x03FC5E;
  constexpr uint16_t Drip_59_width  = 128;
  constexpr uint16_t Drip_59_height = 64;

  constexpr uint24_t Drip_60 = 0x040462;
  constexpr uint16_t Drip_60_width  = 128;
  constexpr uint16_t Drip_60_height = 64;

  constexpr uint24_t Zoom = 0x040C66;
  constexpr uint24_t Zoom1 = 0x040DB0;
}

